### ISSUE TITLE
TwitterのOAuth後のCallbackのresponseにoauth_token_secretがない

### ISSUE THREAD

**Issue by kwbt69** [r-stack/team_e#1]
views.pyのここね↓
user.oauth_token_secret = response["oauth_token_secret"]

これがないと困るわ。

**Comment by tomoyuki-nakabayashi** [comment]
土田さんが言っていた個人アカウントのsecret keyでしょうか？
twitterでdeveloper登録すると取得できたと思いますが、違っていたらごめんなさい。

**Comment by kwbt69** [comment]
@tomoyuki-nakabayashi 大丈夫、解決しました。最新のmasterではTweetをとってくるところまでできてます。もーちょいでDOMまでははけそう。

**Comment by tomoyuki-nakabayashi** [comment]
さすがです！
何か私が手伝えそうなところありますか？
勉強しながらになるので、足手まといかもしれませんが、、、ちょっとでもお役に立てればと。
後、中々手を出せない分野なので、勉強の機会にしたいというのもありますが！

**Comment by kwbt69** [comment]
@tomoyuki-nakabayashi まじすか！もっすごいありがたいです！

もしよければ、このあたりをやってみませんか？　やってみたいほうを教えてください。
- 東京都知事選の候補者のTweetをひろってきて言語解析＆カテゴリのリスト変換してDBに納める的な部分
- BootstrapとかでDOMをレスポンシブかつオサレにする部分

上の方は仕掛かり中ですがコードを上げておきました。雰囲気はつかめるかも・・・
https://github.com/r-stack/team_e/tree/feature/candidate

そのほかは、あとで機能案とかバグとかでIssue切るので、拾えるところを拾ってください。
拾うところは自分にAssignしてからやってもらえると、重複を避けられます。
