### ISSUE TITLE
30秒は待たされ感がある件

### ISSUE THREAD

**Issue by kwbt69** [r-stack/team_e#10]
ツイート1件からカテゴリ抽出するためのJetrunテクノロジさんの言語解析API呼び出し、1件おきに0.3秒あけてますが、100ツイートなげると30秒かかってしまいます。
長い・・・。

まずはアイデア募集。
30秒待つこと前提に、楽しんで待ってもらう案もあり。

**Comment by kiikura** [comment]
そうなんだよね。そこらへんのコアロジックはわかんないからストリーム的に処理できるかわからないしなぁ。

30秒間を楽しませるというアイデアはいいね。  
例えば、今回の争点とか、立候補者一覧とか事前に準備できるコンテンツを流せばいいんだもんね。
- chunkごとにフラッシュして進んでる感出す。（今の見た目ならいいんだけど）
- ajax化して途中経過を出すことでごまかす
- バックグラウンドで収集する
- jetrun側がまとめて（バルク的に）呼べない？
- キャッシュできる部分ないかな

**Comment by tomoyuki-nakabayashi** [comment]
ドコモAPIでは、1回のリクエストにつき、500文字まで受付されます。複数のツイートを１つにまとめれば、待ち時間は3分の1程度には削減できると思います。(1ツイート140文字以内なので)
ただ、それでも長いので、ブラスアルファの案が必要ですね。

**Comment by kiikura** [comment]
:+1: 初手としていいと思います。月間5000リクエスト制限もあるのでそっちにも効果ありますね。

**Comment by kwbt69** [comment]
まずはライトに複数ツイートまとめ案を試してみます。
ただし、複数ツイートをひとつにまとめると、マッチングのロジック再考が必要そうです。ツイートって、それぞれテーマが違うはず。複数ツイートをまとめて評価すると、丸められちゃいます。中身のスコアを使ってゴニョゴニョするかも。

**Comment by kwbt69** [comment]
これも #14 で一緒になおしておきました。
