### ISSUE TITLE
BootstrapとかでDOMをレスポンシブかつオサレにする

### ISSUE THREAD

**Issue by kwbt69** [r-stack/team_e#5]

**Comment by kiikura** [comment]
いい雰囲気ですね。お手伝いさせてください。forkしてるんだけど適当にプルリクすればいい？

**Comment by kwbt69** [comment]
@kiikura あざっす！オナシャス！

**Comment by kiikura** [comment]
@kwbt69 トップ画面に説明としてプロト以上の内容を出す予定ある？スクロールなしで実装しようとしてますけど。

**Comment by kwbt69** [comment]
1行説明を足そうかと思ってますが、スクロールなしで大丈夫です。例えば、あなたと似た発言をしている都知事選候補者を見つけます、みたいな。
