### ISSUE TITLE
ログイン画面を表示するView(URL)がよくわかんないよ

### ISSUE THREAD

**Issue by kiikura** [r-stack/team_e#8]
/loginへのアクセスが丸ごとTwitterにリダイレクトしてますが、ログイン画面を表示するのはどこに行きましたか？  
index.htmlがログイン画面のテンプレートっぽいのですがそれを使っているところが見当たりません。（元々は/にマップされていました。）
- social auth使わなくなってますけど意図的なものですか？
  - social authは確かdjango の contrib authと関連づいてたからcontrib auth使ってないということはそういうアプローチにしたってことであってます？

**Comment by kiikura** [comment]
@kwbt69 メンションしたほーがいいのかな

**Comment by kwbt69** [comment]
@kiikura ログイン画面は一旦はずしてます。これはこれでありかな、ともちょっと思ったのですが、ログイン画面で最低限ナニモノかを説明したいので、あとで作ろうと思ってます。

> social auth使わなくなってますけど意図的なものですか？
> social authは確かdjango の contrib authと関連づいてたからcontrib auth使ってないということはそういうアプローチにしたってことであってます？

認識あってます。

もともと index でpython-social-authを使ってログインを実装してましたが、いまは使っていません。
twitter-timelineでpython-twitterのOAuthを使っていたので、まずはWeb画面から一連の動作を流すことを優先してpython-twitterでOAuthのトークンをとってきて、Userにつっこんでます。
Twitterだけなら、これでいいかな、と。

もし将来的にFacebookやらなにやらを考えるなら、あらためてpython-social-authでいきたいです。

**Comment by kiikura** [comment]
了解したよ。

トップ画面なくなったってtwitterで代替するってことね。protのトップ画面作ろうと思ってハマったので・・・。

ログイン/非ログイン状態を管理するなら、python-social-auth + contrib.auth使った方がシンプルに実装できますが、python-social-auth版作っとこうか？

Userってモデルがすこし混乱を招くし、現在のcandidateと競合するけど・・・、  2.0 hあればいけますよ。
（何故ならすでにpython-social-authでも動くようになってるから）

ちなみにurlsに記載のあるloginとcallbackのビューは両方ともなくなります。（authのviewとsocialのviewをそれぞれ使うことになるので）

**Comment by kwbt69** [comment]
@kiikura まじすか。オナシャス！いまはわりとむりくりセッション管理やってるので・・・。
